/**
 * nusys_patches.cpp – PC replacements for NuSystem API stubs.
 *
 * The N64Recomp configuration (hm64.us.toml) stubs out all nuGfx* and
 * nuCont* functions so the runtime can intercept them.  This file provides
 * the implementations that bridge between the recompiled game code and the
 * ultramodern runtime.
 *
 * The macro signatures here follow the N64ModernRuntime librecomp convention:
 *   void RECOMP_FUNC(uint8_t* rdram, recomp_context* ctx);
 * where arguments/return values are accessed through the ctx register file.
 */

#include "librecomp/recomp.h"
#include "ultramodern/ultramodern.hpp"

#include <atomic>

// ---------------------------------------------------------------------------
// Forward declaration for the recompiled gfxRetraceCallback.
// Generated by n64recomp; the naming follows the decomp symbol name.
// ---------------------------------------------------------------------------
extern "C" void recomp_gfxRetraceCallback(uint8_t* rdram, recomp_context* ctx);

// ---------------------------------------------------------------------------
// Retrace-callback state
// ---------------------------------------------------------------------------
// Set once by nuGfxFuncSet (game thread) and read each frame by the render
// thread via hm64_invoke_retrace_callback().  Atomic for safe cross-thread
// access; the rdram pointer is a fixed allocation that never changes after
// ultramodern::start() is called.
static std::atomic<uint8_t*> s_rdram{nullptr};
static std::atomic<bool>     s_retrace_registered{false};

// ---------------------------------------------------------------------------
// hm64_invoke_retrace_callback
// ---------------------------------------------------------------------------
// Called from graphics::render_frame (render thread) once per vsync to drive
// the game's retrace mechanism.  This replicates the role that NuSystem's
// nuSched graphics thread played on real N64 hardware:
//   • readControllerData()       – refresh controller state from ultramodern
//   • handleGraphicsUpdate()     – call drawFrame() if a frame slot is free
//   • updateMainLoopTimer()      – set stepMainLoop = TRUE, unblocking
//                                  the game thread's busy-wait in mainLoop()
void hm64_invoke_retrace_callback() {
    uint8_t* rdram = s_rdram.load(std::memory_order_acquire);
    if (rdram == nullptr || !s_retrace_registered.load(std::memory_order_acquire)) {
        return;
    }
    recomp_context ctx{};
    ctx.r4 = 0; // pendingGfx = 0 (no outstanding RSP tasks at vsync entry)
    recomp_gfxRetraceCallback(rdram, &ctx);
}

// ---------------------------------------------------------------------------
// nuGfxInit  – replaced by ultramodern graphics initialisation
// ---------------------------------------------------------------------------
RECOMP_PATCH void nuGfxInit(uint8_t* rdram, recomp_context* ctx) {
    // ultramodern initialises graphics when the renderer callback fires;
    // nothing to do here at startup.
}

// ---------------------------------------------------------------------------
// nuGfxTaskStart – submit an RSP/RDP display list
// ---------------------------------------------------------------------------
RECOMP_PATCH void nuGfxTaskStart(uint8_t* rdram, recomp_context* ctx) {
    // a0 = gfxList pointer (N64 virtual address)
    // a1 = list size in bytes
    // a2 = ucode type (NU_GFX_UCODE_F3DEX etc.)
    // a3 = swap-buffer flag
    gpr gfx_list_ptr  = ctx->r4;
    gpr list_size     = ctx->r5;
    gpr ucode_type    = ctx->r6;
    gpr swap_flag     = ctx->r7;

    ultramodern::submit_rsp_task(rdram, gfx_list_ptr, list_size,
                                  ucode_type, swap_flag);
}

// ---------------------------------------------------------------------------
// nuGfxTaskAllEndWait – wait for all pending RSP/RDP tasks to finish
// ---------------------------------------------------------------------------
RECOMP_PATCH void nuGfxTaskAllEndWait(uint8_t* rdram, recomp_context* ctx) {
    ultramodern::wait_for_rsp_done();
}

// ---------------------------------------------------------------------------
// nuGfxSwapCfbFuncSet – register the framebuffer-swap callback
// ---------------------------------------------------------------------------
RECOMP_PATCH void nuGfxSwapCfbFuncSet(uint8_t* rdram, recomp_context* ctx) {
    // a0 = function pointer (or NULL to clear)
    // ultramodern handles the swap internally; this is a no-op on PC.
}

// ---------------------------------------------------------------------------
// nuGfxPreNMIFuncSet – register the pre-NMI callback
// ---------------------------------------------------------------------------
RECOMP_PATCH void nuGfxPreNMIFuncSet(uint8_t* rdram, recomp_context* ctx) {
    // No NMI on PC; ignore.
}

// ---------------------------------------------------------------------------
// nuGfxFuncSet – register the retrace (vsync) callback
// ---------------------------------------------------------------------------
// The game calls nuGfxFuncSet(gfxRetraceCallback) during initializeEngine().
// On real hardware, NuSystem's graphics scheduler thread would call this
// function every vsync.  On PC we replicate that by calling it from the
// render thread inside graphics::render_frame (see hm64_invoke_retrace_callback
// above).  Passing NULL clears the registration (used by gfxPreNMICallback).
RECOMP_PATCH void nuGfxFuncSet(uint8_t* rdram, recomp_context* ctx) {
    // a0 = NUGfxFunc callback pointer, or 0 to deregister.
    s_rdram.store(rdram, std::memory_order_release);
    s_retrace_registered.store(ctx->r4 != 0, std::memory_order_release);
}

// ---------------------------------------------------------------------------
// nuGfxDisplayOn / nuGfxDisplayOff
// ---------------------------------------------------------------------------
RECOMP_PATCH void nuGfxDisplayOn(uint8_t* rdram, recomp_context* ctx) {
    ultramodern::set_display_enabled(true);
}

RECOMP_PATCH void nuGfxDisplayOff(uint8_t* rdram, recomp_context* ctx) {
    ultramodern::set_display_enabled(false);
}

// ---------------------------------------------------------------------------
// nuContInit / nuContDataGetAll – controller handling
// ---------------------------------------------------------------------------
RECOMP_PATCH void nuContInit(uint8_t* rdram, recomp_context* ctx) {
    // ultramodern provides controller data; nothing to initialise here.
}

RECOMP_PATCH void nuContDataGetAll(uint8_t* rdram, recomp_context* ctx) {
    // Called each frame to refresh the nuContData[] array.
    // ultramodern populates this through the input callback.
    ultramodern::update_input(rdram);
}

// ---------------------------------------------------------------------------
// nuContDataGet – refresh controller data for n controllers
// ---------------------------------------------------------------------------
// Like nuContDataGetAll but for an explicit count (a0).  We simply refresh
// all controller state the same way; ultramodern handles the indexing.
RECOMP_PATCH void nuContDataGet(uint8_t* rdram, recomp_context* ctx) {
    ultramodern::update_input(rdram);
}
