/**
 * nusys_patches.cpp – PC replacements for NuSystem API stubs.
 *
 * The N64Recomp configuration (hm64.us.toml) stubs out most nuGfx* and
 * nuCont* functions so the runtime can intercept them.  This file provides
 * the implementations that bridge between the recompiled game code and the
 * ultramodern runtime.
 *
 * Functions NOT patched here (recompiled game code runs directly):
 *   nuGfxInit      – runs as-is; initialises nuGfxCfb_ptr, nuGfxZBuffer, and
 *                    nuGfxUcode from the game's FrameBuf / Z-buffer constants.
 *                    The NuSystem threading calls inside it (nuGfxThreadStart,
 *                    nuGfxTaskMgrInit) are stubbed in hm64.us.toml so they
 *                    do nothing; ultramodern provides its own task execution.
 *   nuGfxSetCfb    – pure data: sets nuGfxCfb_ptr = framebuf[0] in RDRAM.
 *                    Removed from stubs so the recompiled version updates
 *                    the framebuffer globals that clearFramebuffer() reads.
 *
 * The macro signatures here follow the N64ModernRuntime librecomp convention:
 *   void RECOMP_FUNC(uint8_t* rdram, recomp_context* ctx);
 * where arguments/return values are accessed through the ctx register file.
 */

#include "librecomp/recomp.h"
#include "ultramodern/ultramodern.hpp"

#include <atomic>

// ---------------------------------------------------------------------------
// Forward declaration for the recompiled gfxRetraceCallback.
// Generated by n64recomp; the naming follows the decomp symbol name.
// ---------------------------------------------------------------------------
extern "C" void recomp_gfxRetraceCallback(uint8_t* rdram, recomp_context* ctx);

// ---------------------------------------------------------------------------
// Retrace-callback state
// ---------------------------------------------------------------------------
// Set once by nuGfxFuncSet (game thread) and read each frame by the render
// thread via hm64_invoke_retrace_callback().  Atomic for safe cross-thread
// access; the rdram pointer is a fixed allocation that never changes after
// ultramodern::start() is called.
static std::atomic<uint8_t*> s_rdram{nullptr};
static std::atomic<bool>     s_retrace_registered{false};

// ---------------------------------------------------------------------------
// hm64_invoke_retrace_callback
// ---------------------------------------------------------------------------
// Called from graphics::render_frame (render thread) once per vsync to drive
// the game's retrace mechanism.  This replicates the role that NuSystem's
// nuSched graphics thread played on real N64 hardware:
//   • readControllerData()       – refresh controller state from ultramodern
//   • handleGraphicsUpdate()     – call drawFrame() if a frame slot is free
//   • updateMainLoopTimer()      – set stepMainLoop = TRUE, unblocking
//                                  the game thread's busy-wait in mainLoop()
void hm64_invoke_retrace_callback() {
    uint8_t* rdram = s_rdram.load(std::memory_order_acquire);
    if (rdram == nullptr || !s_retrace_registered.load(std::memory_order_acquire)) {
        return;
    }
    recomp_context ctx{};
    ctx.r4 = 0; // pendingGfx = 0 (no outstanding RSP tasks at vsync entry)
    recomp_gfxRetraceCallback(rdram, &ctx);
}

// ---------------------------------------------------------------------------
// nuGfxTaskStart – submit an RSP/RDP display list
// ---------------------------------------------------------------------------
RECOMP_PATCH void nuGfxTaskStart(uint8_t* rdram, recomp_context* ctx) {
    // a0 = gfxList pointer (N64 virtual address)
    // a1 = list size in bytes
    // a2 = ucode type (NU_GFX_UCODE_F3DEX etc.)
    // a3 = swap-buffer flag
    gpr gfx_list_ptr  = ctx->r4;
    gpr list_size     = ctx->r5;
    gpr ucode_type    = ctx->r6;
    gpr swap_flag     = ctx->r7;

    ultramodern::submit_rsp_task(rdram, gfx_list_ptr, list_size,
                                  ucode_type, swap_flag);
}

// ---------------------------------------------------------------------------
// nuGfxTaskAllEndWait – wait for all pending RSP/RDP tasks to finish
// ---------------------------------------------------------------------------
RECOMP_PATCH void nuGfxTaskAllEndWait(uint8_t* rdram, recomp_context* ctx) {
    ultramodern::wait_for_rsp_done();
}

// ---------------------------------------------------------------------------
// nuGfxSwapCfbFuncSet – register the framebuffer-swap callback
// ---------------------------------------------------------------------------
RECOMP_PATCH void nuGfxSwapCfbFuncSet(uint8_t* rdram, recomp_context* ctx) {
    // a0 = function pointer (or NULL to clear)
    // ultramodern handles the swap internally; this is a no-op on PC.
}

// ---------------------------------------------------------------------------
// nuGfxPreNMIFuncSet – register the pre-NMI callback
// ---------------------------------------------------------------------------
RECOMP_PATCH void nuGfxPreNMIFuncSet(uint8_t* rdram, recomp_context* ctx) {
    // No NMI on PC; ignore.
}

// ---------------------------------------------------------------------------
// nuGfxFuncSet – register the retrace (vsync) callback
// ---------------------------------------------------------------------------
// The game calls nuGfxFuncSet(gfxRetraceCallback) during initializeEngine().
// On real hardware, NuSystem's graphics scheduler thread would call this
// function every vsync.  On PC we replicate that by calling it from the
// render thread inside graphics::render_frame (see hm64_invoke_retrace_callback
// above).  Passing NULL clears the registration (used by gfxPreNMICallback).
RECOMP_PATCH void nuGfxFuncSet(uint8_t* rdram, recomp_context* ctx) {
    // a0 = NUGfxFunc callback pointer, or 0 to deregister.
    s_rdram.store(rdram, std::memory_order_release);
    s_retrace_registered.store(ctx->r4 != 0, std::memory_order_release);
}

// ---------------------------------------------------------------------------
// nuGfxDisplayOn / nuGfxDisplayOff
// ---------------------------------------------------------------------------
RECOMP_PATCH void nuGfxDisplayOn(uint8_t* rdram, recomp_context* ctx) {
    ultramodern::set_display_enabled(true);
}

RECOMP_PATCH void nuGfxDisplayOff(uint8_t* rdram, recomp_context* ctx) {
    ultramodern::set_display_enabled(false);
}

// ---------------------------------------------------------------------------
// nuContInit / nuContDataGetAll / nuContDataGetExAll – controller handling
// ---------------------------------------------------------------------------
RECOMP_PATCH void nuContInit(uint8_t* rdram, recomp_context* ctx) {
    // Return 0x01 to report that controller port 1 is connected.
    // The game's setupGameStart() checks (contPattern & 1): if true it
    // launches the intro cutscene / title screen; if false it shows the
    // "No Controller" message instead.  On PC, keyboard and gamepad are
    // always mapped to port 1, so we unconditionally report it present.
    ctx->r2 = 0x01;
}

RECOMP_PATCH void nuContDataGetAll(uint8_t* rdram, recomp_context* ctx) {
    // Called each frame to refresh the nuContData[] array.
    // ultramodern populates this through the input callback.
    ultramodern::update_input(rdram);
}

// ---------------------------------------------------------------------------
// nuContDataGetExAll – extended controller data refresh (all ports)
// ---------------------------------------------------------------------------
// Like nuContDataGetAll but also refreshes nuContStatus[] (type/errno).
// readControllerData() calls this every frame; without a patch the recompiled
// NuSystem code tries to access real SI hardware and hangs.
// ultramodern::update_input already fills in button/stick data for all ports;
// nuContStatus[] stays BSS-zero-initialised (errno=0) so the data is used.
RECOMP_PATCH void nuContDataGetExAll(uint8_t* rdram, recomp_context* ctx) {
    ultramodern::update_input(rdram);
}

// ---------------------------------------------------------------------------
// nuContDataGet – refresh controller data for n controllers
// ---------------------------------------------------------------------------
// Like nuContDataGetAll but for an explicit count (a0).  We simply refresh
// all controller state the same way; ultramodern handles the indexing.
RECOMP_PATCH void nuContDataGet(uint8_t* rdram, recomp_context* ctx) {
    ultramodern::update_input(rdram);
}

// ---------------------------------------------------------------------------
// nuContPak* – Controller Pak (memory card) API stubs
// ---------------------------------------------------------------------------
// HM64 saves via SRAM (handled by sram_patches.cpp), not the Controller Pak.
// These functions are provided as safe no-ops so that any code path that
// probes for a pak returns "no pak present" without crashing.
//
// nuContPakOpen sets pak.error = NU_CONT_PAK_ERR_EMPTY (1) to signal that
// no pak is inserted; the caller checks this and skips pak operations.

// NUContPak is a NuSystem struct; we only need to set its error field which
// is at a known offset (offsetof(NUContPak, error) == 0 in nuContPak.h).
// Rather than pulling in NuSystem headers, we write the errno byte directly
// via the rdram pointer using the N64 virtual address in a0.
// Layout from nuContPak.h:  NUContPak { NUContPakHandle pak; ... }
// pak.error is the first field after the OSPfs handle; for our purposes we
// just set the whole struct's first word to a non-zero error code so callers
// see "pak absent" and short-circuit without further pak operations.

// Offset of the error field within NUContPak.pak (OSPfs).
// OSPfs layout: [OSPiHandle* handle (4 bytes)] [u32 channel (4 bytes)] [u8 error (1 byte)]
// pak.error lives at byte offset 8 from the NUContPak base.
static constexpr uint32_t CONT_PAK_ERROR_OFFSET = 8;

RECOMP_PATCH void nuContPakOpen(uint8_t* rdram, recomp_context* ctx) {
    // a0 = NUContPak* (N64 virtual address), a1 = controller index
    // Write error = 1 (NU_CONT_PAK_ERR_EMPTY) so callers see no pak present.
    // NUContPak.pak is an OSPfs which begins with OSFileHandle (OSPiHandle*,
    // 4-byte pointer) then a 4-byte "channel" word, then at offset 8 the
    // error byte.  We set offset 8 = 1.
    uint32_t pak_vaddr = (uint32_t)ctx->r4;
    if (pak_vaddr) {
        uint32_t phys = pak_vaddr & 0x1FFFFFFF;
        rdram[phys + CONT_PAK_ERROR_OFFSET] = 1; // pak.error = 1 (NU_CONT_PAK_ERR_EMPTY)
    }
}

RECOMP_PATCH void nuContPakRepairId(uint8_t* rdram, recomp_context* ctx) {
    // No pak; nothing to repair.
}

RECOMP_PATCH void nuContPakGetFree(uint8_t* rdram, recomp_context* ctx) {
    ctx->r2 = 0; // 0 free pages
}

RECOMP_PATCH void nuContPakFileNum(uint8_t* rdram, recomp_context* ctx) {
    // a0 = NUContPak*, a1 = *max_files (s32*), a2 = *used_files (s32*)
    // Write 32-bit zero to both output pointers (4 bytes each, BE or zero = same).
    uint32_t max_ptr  = (uint32_t)ctx->r5;
    uint32_t used_ptr = (uint32_t)ctx->r6;
    if (max_ptr) {
        uint32_t phys = max_ptr & 0x1FFFFFFF;
        rdram[phys+0] = rdram[phys+1] = rdram[phys+2] = rdram[phys+3] = 0;
    }
    if (used_ptr) {
        uint32_t phys = used_ptr & 0x1FFFFFFF;
        rdram[phys+0] = rdram[phys+1] = rdram[phys+2] = rdram[phys+3] = 0;
    }
}

RECOMP_PATCH void nuContPakCodeSet(uint8_t* rdram, recomp_context* ctx) {
    // No-op; no pak to set a company/game code on.
}

RECOMP_PATCH void nuContPakFileOpenJis(uint8_t* rdram, recomp_context* ctx) {
    // a0 = NUContPak* – mark pak error so callers skip the operation.
    uint32_t pak_vaddr = (uint32_t)ctx->r4;
    if (pak_vaddr) {
        rdram[(pak_vaddr & 0x1FFFFFFF) + CONT_PAK_ERROR_OFFSET] = 1;
    }
}

RECOMP_PATCH void nuContPakFileReadWrite(uint8_t* rdram, recomp_context* ctx) {
    // No pak; no data to read or write.
}

RECOMP_PATCH void nuContPakFileDeleteJis(uint8_t* rdram, recomp_context* ctx) {
    // No pak; nothing to delete.
}

// ---------------------------------------------------------------------------
// osEPiLinkHandle – register an OSPiHandle with the OS PI subsystem
// ---------------------------------------------------------------------------
// Called from sramInit() before any DMA.  On PC, osEPiStartDma is already
// a no-op stub, so the actual transfer never happens.  The handle setup in
// sramInit is skipped entirely when sramLoad/sramWrite are patched directly
// (see sram_patches.cpp), but we provide this stub as a safety net for any
// remaining call site.
RECOMP_PATCH void osEPiLinkHandle(uint8_t* rdram, recomp_context* ctx) {
    // No PI hardware on PC; no-op.
}
